name: CI

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Test with Scala 2.11
      run: sbt "++ 2.11.12 test"
    - name: Test with Scala 2.12
      run: sbt "++ 2.12.11 test"
    - name: Test with Scala 2.13
      run: sbt "++ 2.13.1 test"

